Traceback (most recent call last):
  File "/home/dmitry/zeev/python2to3/venv/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/dmitry/zeev/python2to3/venv/lib/python3.7/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/dmitry/zeev/python2to3/venv/lib/python3.7/site-packages/pylint/lint/run.py", line 308, in __init__
    linter.load_plugin_modules(plugins)
  File "/home/dmitry/zeev/python2to3/venv/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 490, in load_plugin_modules
    module = modutils.load_module_from_name(modname)
  File "/home/dmitry/zeev/python2to3/venv/lib/python3.7/site-packages/astroid/modutils.py", line 203, in load_module_from_name
    return load_module_from_modpath(dotted_name.split("."), path, use_sys)
  File "/home/dmitry/zeev/python2to3/venv/lib/python3.7/site-packages/astroid/modutils.py", line 244, in load_module_from_modpath
    mp_file, mp_filename, mp_desc = imp.find_module(part, path)
  File "/usr/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'caniusepython3'
